
workflows:
  ios-workflow:
    name: SmartAlarm Build
    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Build
        script: |
          xcodebuild -list

    artifacts:
      - build/**/*.ipa
